version: "3.8"

services:
  authservice:
    build:
      context: .
      dockerfile: GO-AuthService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
